[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM8
upload_speed = 115200
upload_protocol = arduino
upload_resetmethod = arduino
lib_deps =
    adafruit/DHT sensor library@^1.4.7
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^6.21.5
monitor_speed = 9600